[package]
name = "reverse-string"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-reverse = "1.0.8"
unicode-segmentation = "1.9.0"

[features]
grapheme = []
